# Number of days of inactivity before an issue becomes stale
daysUntilStale: 120
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Aloha!
  I'm ScissorBot :scissors: -- the bot in charge of keeping the issues tidy.
  It looks like this issue is stale due to lack of activity. Unfortunately, I'll be closing it if there is no further activity. 😞  
  Please contribute to the issue to keep it open.
  Thanks!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
